In [103]:
import pandas as pd
import os
import matplotlib.pyplot as plt
os.chdir ("C:\\Users\\Hp\\Desktop\\Chaimae\\stage\\PFE\\Dataset\\clean_data")
cwd=os.getcwd()
print(cwd)
df=pd.read_excel('dataprepro.xlsx')

C:\Users\Hp\Desktop\Chaimae\stage\PFE\Dataset\clean_data

In [104]:
df.head()

,Id_User,Ville de depart,Latitude,Longitude,Ville d'arrivée,Latitude.1,Longitude.1,Distance,prix,Year_dep,...,Hour_dep,minute_dep,day_arr,weekday_name_arr,minute_arr,Hour_arr,hour_duree,minute_duree,nombre_place,Moyen_de_transport
0,74517,RABAT,34.022405,-6.834543,CASABLANCA,33.595063,-7.618777,92.718000,18.5436,2018,...,21,31,31,Tuesday,31,21,1,7,4,Voiture
1,90486,CASABLANCA,33.595063,-7.618777,TAZA,34.230155,-4.010104,403.209999,80.6420,2018,...,11,12,29,Sunday,12,11,3,50,2,Voiture
2,69046,KHENIFRA,32.935772,-5.669650,AGADIR,30.422037,-9.559509,649.335999,194.8008,2018,...,6,24,15,Sunday,24,6,19,29,2,Voiture
3,86417,RABAT,34.022405,-6.834543,TETOUAN,35.570175,-5.374278,270.819000,81.2457,2018,...,6,0,5,Wednesday,0,6,9,33,2,Voiture
4,79358,OUARZAZATE,30.920193,-6.910923,TEMARA,33.917166,-6.923804,509.914999,142.7762,2018,...,15,30,23,Wednesday,30,15,5,39,4,Voiture

In [108]:
df.drop(['Ville de depart','Latitude','Longitude',"Latitude.1","Longitude.1","Ville d'arrivée",'weekday_name_dep',"weekday_name_arr"],axis=1,inplace=True)

In [105]:
df.isnull().sum().sum()

0

In [106]:
from sklearn import preprocessing
import numpy as np
# Import the encoder from sklearn
le = preprocessing.LabelEncoder()

# Encode the features
df['encoded_ville_dep']=le.fit_transform(df['Ville de depart'])
df['encoded_ville_arr']=le.fit_transform(df["Ville d'arrivée"])
df['encoded_weekday_name_dep']=le.fit_transform(df['weekday_name_dep'])
df['encoded_weekday_name_arr']=le.fit_transform(df['weekday_name_arr'])

In [109]:
df.head()

,Id_User,Distance,prix,Year_dep,Month_dep,day_dep,Hour_dep,minute_dep,day_arr,minute_arr,Hour_arr,hour_duree,minute_duree,nombre_place,Moyen_de_transport,encoded_ville_dep,encoded_ville_arr,encoded_weekday_name_dep,encoded_weekday_name_arr
0,74517,92.718000,18.5436,2018,7,31,21,31,31,31,21,1,7,4,Voiture,22,5,5,5
1,90486,403.209999,80.6420,2018,4,29,11,12,29,12,11,3,50,2,Voiture,5,28,3,3
2,69046,649.335999,194.8008,2018,7,15,6,24,15,24,6,19,29,2,Voiture,13,0,3,3
3,86417,270.819000,81.2457,2018,12,5,6,0,5,0,6,9,33,2,Voiture,22,30,6,6
4,79358,509.914999,142.7762,2018,5,23,15,30,23,30,15,5,39,4,Voiture,19,29,6,6

In [91]:
df.isnull().sum().sum()

0

In [110]:
#Creating the dependent variable class
factor = pd.factorize(df['Moyen_de_transport'])
df.Moyen_de_transport = factor[0]
definitions = factor[1]
print(df.Moyen_de_transport.head())
print(definitions)

0    0
1    0
2    0
3    0
4    0
Name: Moyen_de_transport, dtype: int64
Index(['Voiture', 'CTM', 'autocar'], dtype='object')

In [111]:
df1=df[['Id_User','encoded_ville_dep','encoded_ville_arr','Distance','prix','Year_dep','Month_dep','day_dep','encoded_weekday_name_dep','Hour_dep','minute_dep','day_arr','encoded_weekday_name_arr','minute_arr','Hour_arr','hour_duree','minute_duree','nombre_place','Moyen_de_transport']]

In [160]:
df1

,Id_User,encoded_ville_dep,encoded_ville_arr,Distance,prix,Year_dep,Month_dep,day_dep,encoded_weekday_name_dep,Hour_dep,minute_dep,day_arr,encoded_weekday_name_arr,minute_arr,Hour_arr,hour_duree,minute_duree,nombre_place,Moyen_de_transport
0,74517,22,5,92.718000,18.54360,2018,7,31,5,21,31,31,5,31,21,1,7,4,0
1,90486,5,28,403.209999,80.64200,2018,4,29,3,11,12,29,3,12,11,3,50,2,0
2,69046,13,0,649.335999,194.80080,2018,7,15,3,6,24,15,3,24,6,19,29,2,0
3,86417,22,30,270.819000,81.24570,2018,12,5,6,6,0,5,6,0,6,9,33,2,0
4,79358,19,29,509.914999,142.77620,2018,5,23,6,15,30,23,6,30,15,5,39,4,0
5,88786,8,28,770.075000,192.51875,2018,8,14,5,11,24,14,5,24,11,7,28,1,0
6,95432,20,30,127.446999,35.68516,2019,3,2,2,13,0,2,2,0,13,1,57,1,0
7,73903,19,2,299.233000,83.78524,2019,1,24,2,15,38,24,2,38,15,4,34,3,0
8,98425,5,19,437.146000,196.71570,2018,4,3,2,17,37,3,2,37,17,10,22,15,1
9,93117,19,2,299.233000,134.65485,2018,6,8,2,23,44,8,2,44,23,9,8,16,1
10,96719,4,7,591.270000,266.07150,2018,4,27,2,19,49,27,2,49,19,14,13,7,1
11,73280,6,21,710.254000,142.05080,2018,12,22,2,13,21,22,2,21,13,6,26,2,0
12,80519,17,19,459.326000,137.79780,2019,3,23,2,14,17,23,2,17,14,15,45,2,0
13,98958,8,21,980.945000,294.28350,2018,11,9,2,6,56,9,2,56,6,3,56,2,0
14,13336,6,10,382.694000,107.15432,2019,3,4,2,7,56,4,2,56,7,4,31,3,0
15,30213,14,22,208.590999,52.14775,2019,2,7,2,8,32,7,2,32,8,2,6,1,0
16,49455,5,22,92.925000,18.58500,2018,11,28,2,19,44,28,2,44,19,1,7,1,0
17,99552,15,8,174.899000,78.70455,2019,1,15,2,15,49,15,2,49,15,4,50,7,1
18,33912,22,27,248.345000,49.66900,2018,6,3,2,11,33,3,2,33,11,2,36,4,0
19,64796,29,4,114.127999,22.82560,2018,11,20,2,20,49,20,2,49,20,1,9,4,0
20,71094,13,12,171.472000,48.01216,2018,7,21,2,17,36,21,2,36,17,2,11,1,0
21,67045,13,3,485.136000,135.83808,2018,7,26,2,21,31,26,2,31,21,5,10,3,0
22,87940,8,27,711.917000,213.57510,2019,2,20,2,11,11,20,2,11,11,7,3,2,0
23,98233,8,15,174.962001,48.98936,2018,11,20,2,16,5,20,2,5,16,2,24,2,0
24,48079,16,28,173.115999,51.93480,2019,3,14,2,20,39,14,2,39,20,5,16,19,2
25,71140,4,26,259.677999,51.93560,2018,12,22,2,9,5,22,2,5,9,2,47,1,0
26,51029,14,18,591.152000,266.01840,2018,10,20,2,23,46,20,2,46,23,12,54,14,1
27,98590,13,3,485.136000,97.02720,2018,11,16,2,8,11,16,2,11,8,5,10,3,0
28,97876,30,13,382.985000,114.89550,2018,9,24,2,17,52,24,2,52,17,5,20,1,0
29,98100,3,5,610.013000,152.50325,2019,1,17,2,17,34,17,2,34,17,5,54,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
688689,33912,18,10,1043.274000,469.47330,2018,8,28,5,23,33,28,5,33,23,19,35,20,1
688690,91720,4,6,101.220000,20.24400,2019,1,10,4,6,14,10,4,14,6,1,8,1,0
688691,60202,2,25,217.455001,43.49100,2018,8,15,6,21,16,15,6,16,21,2,7,2,0
688692,84764,29,14,138.085000,41.42550,2018,6,25,1,7,40,25,1,40,7,2,0,4,0
688693,82975,20,4,307.269000,92.18070,2019,3,13,6,21,25,13,6,25,21,3,20,4,0
688694,68111,1,14,558.444000,156.36432,2018,4,17,5,15,59,17,5,59,15,6,34,4,0
688695,86954,4,5,39.395000,9.84875,2018,12,19,6,18,40,19,6,40,18,0,38,2,0
688696,55981,6,10,382.694000,114.80820,2019,2,17,3,13,45,17,3,45,13,4,31,3,0
688697,9948,8,1,925.049999,185.01000,2018,8,31,0,8,54,31,0,54,8,9,36,3,0
688698,85511,11,16,146.035000,40.88980,2018,3,25,3,7,3,25,3,3,7,1,35,2,0
688699,44508,4,1,589.680001,265.35600,2019,1,11,0,10,40,11,0,40,10,12,24,14,1
688700,95249,26,15,462.358000,129.46024,2018,8,30,4,9,3,30,4,3,9,4,38,1,0
688701,99825,13,5,262.693001,118.21185,2018,5,17,4,9,15,17,4,15,9,6,15,8,1
688702,92576,5,8,374.895999,74.97920,2018,8,2,4,10,25,2,4,25,10,4,4,2,0
688703,99037,30,9,349.205000,97.77740,2018,6,22,0,16,34,22,0,34,16,4,53,1,0
688704,44799,29,3,524.187000,235.88415,2018,8,31,0,19,20,31,0,20,19,10,18,12,1
688705,85547,15,0,247.197001,49.43940,2018,8,25,2,17,33,25,2,33,17,2,36,1,0
688706,88587,8,6,279.356000,69.83900,2019,2,14,4,15,35,14,4,35,15,3,11,3,0
688707,97012,17,22,66.145001,13.22900,2018,10,10,6,23,3,10,6,3,23,0,49,2,0
688708,98105,9,5,374.449001,104.84572,2019,1,29,5,9,9,29,5,9,9,3,44,3,0
688709,58874,9,5,374.449001,104.84572,2018,6,14,4,18,26,14,4,26,18,3,44,3,0
688710,90833,28,19,834.569001,208.64225,2018,6,7,4,17,49,7,4,49,17,8,35,4,0
688711,68108,2,14,85.818999,17.16380,2018,5,20,3,8,41,20,3,41,8,1,14,2,0
688712,97369,21,23,854.498999,256.34970,2019,1,22,5,19,48,22,5,48,19,23,6,33,2
688713,92987,15,12,415.999001,187.19955,2018,11,25,3,23,55,25,3,55,23,7,52,17,1
688714,76634,19,0,357.970001,71.59400,2018,8,21,5,10,36,21,5,36,10,4,41,2,0
688715,93023,12,16,68.360000,19.14080,2018,8,11,2,22,0,11,2,0,22,0,49,3,0
688716,99781,6,28,499.383999,224.72280,2018,3,31,2,21,17,31,2,17,21,9,12,12,1
688717,93331,16,6,339.399000,95.03172,2019,3,18,1,9,30,18,1,30,9,3,11,4,0
688718,68108,28,6,501.325999,150.39780,2019,2,19,5,17,46,19,5,46,17,13,43,22,2

In [164]:
#Importing Libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.externals import joblib

In [165]:
X = df1.iloc[:,1:18].values
y = df1.iloc[:,18].values
print('The independent features set: ')
print(X[:5,:])
print('The dependent variable: ')
print(y[:18])

The independent features set:
[[2.20000000e+01 5.00000000e+00 9.27179997e+01 1.85435999e+01
  2.01800000e+03 7.00000000e+00 3.10000000e+01 5.00000000e+00
  2.10000000e+01 3.10000000e+01 3.10000000e+01 5.00000000e+00
  3.10000000e+01 2.10000000e+01 1.00000000e+00 7.00000000e+00
  4.00000000e+00]
 [5.00000000e+00 2.80000000e+01 4.03209999e+02 8.06419999e+01
  2.01800000e+03 4.00000000e+00 2.90000000e+01 3.00000000e+00
  1.10000000e+01 1.20000000e+01 2.90000000e+01 3.00000000e+00
  1.20000000e+01 1.10000000e+01 3.00000000e+00 5.00000000e+01
  2.00000000e+00]
 [1.30000000e+01 0.00000000e+00 6.49335999e+02 1.94800800e+02
  2.01800000e+03 7.00000000e+00 1.50000000e+01 3.00000000e+00
  6.00000000e+00 2.40000000e+01 1.50000000e+01 3.00000000e+00
  2.40000000e+01 6.00000000e+00 1.90000000e+01 2.90000000e+01
  2.00000000e+00]
 [2.20000000e+01 3.00000000e+01 2.70819000e+02 8.12457000e+01
  2.01800000e+03 1.20000000e+01 5.00000000e+00 6.00000000e+00
  6.00000000e+00 0.00000000e+00 5.00000000e+00 6.00000000e+00
  0.00000000e+00 6.00000000e+00 9.00000000e+00 3.30000000e+01
  2.00000000e+00]
 [1.90000000e+01 2.90000000e+01 5.09914999e+02 1.42776200e+02
  2.01800000e+03 5.00000000e+00 2.30000000e+01 6.00000000e+00
  1.50000000e+01 3.00000000e+01 2.30000000e+01 6.00000000e+00
  3.00000000e+01 1.50000000e+01 5.00000000e+00 3.90000000e+01
  4.00000000e+00]]
The dependent variable:
[0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 1]

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]

In [135]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [166]:
# Creating the Training and Test set from data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

In [167]:
min_max_scaler = preprocessing.MinMaxScaler()
X_train = min_max_scaler.fit_transform(X_train)
X_test= min_max_scaler.fit_transform(X_test)

In [168]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=40)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)


y_pred=clf.predict(X_test)

In [169]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9941630851434545

In [35]:
print(list(zip(df1.columns[1:22], clf.feature_importances_)))

[('encoded_ville_dep', 0.004979357772516958), ('Latitude', 0.007903075705476489), ('Longitude', 0.007453220566030753), ('encoded_ville_arr', 0.004842990780493848), ('Latitude.1', 0.007343114058591558), ('Longitude.1', 0.0072185837018051355), ('Distance', 0.05875399453909215), ('prix', 0.10519497155007503), ('Year_dep', 0.0003477891305983939), ('Month_dep', 0.0019035043923167913), ('day_dep', 0.002174982733850535), ('encoded_weekday_name_dep', 0.0012825165599608143), ('Hour_dep', 0.001892419750115616), ('minute_dep', 0.0026024159972581166), ('day_arr', 0.0021632518426080677), ('encoded_weekday_name_arr', 0.0012784991942322607), ('minute_arr', 0.0025581762490615952), ('Hour_arr', 0.0018946841957039064), ('hour_duree', 0.1970252007812246), ('minute_duree', 0.012673573184337384), ('nombre_place', 0.5685136773146501)]

In [148]:
from sklearn.model_selection import KFold
kf= KFold(n_splits=5)
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[2 3 4 5 6 7 8] [0 1]
[0 1 4 5 6 7 8] [2 3]
[0 1 2 3 6 7 8] [4 5]
[0 1 2 3 4 5 8] [6 7]
[0 1 2 3 4 5 6 7] [8]

In [149]:
from sklearn.model_selection import StratifiedKFold

In [150]:
score_clf=[]
clf=RandomForestClassifier(n_estimators=40)
for train_index,test_index,in kf.split(X):
    X_train,X_test,y_train,y_test= X[train_index],X[test_index],y[train_index],y[test_index]
    print(get_score(clf,X_train,X_test,y_train,y_test))

0.9999782204669532
0.9999637007782554
0.9999927401556511
0.971004181670345
0.9999491807206173

In [171]:
y=clf.predict(np.array([[21,23,854.498999,256.34970,2019,1,22,5,19,48,22,5,48,19,23,6,33]]))
print(y[0])

2

array([0, 0, 0, ..., 1, 0, 2], dtype=int64)

5

5